# Generated by Django 4.2 on 2023-06-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'ADMIN'), (2, 'ADMINISTRATION'), (3, 'ACCOUNT'), (4, 'EXAM'), (5, 'NOTICE'), (6, 'LIBRARY'), (7, 'LAB'), (8, 'MAINTEINANCE'), (9, 'HOD'), (10, 'STAFF'), (11, 'STUDENT')], default=1, max_length=50),
        ),
    ]
