# Generated by Django 4.2 on 2023-07-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_staff_notice_maintenance_library_lab_hod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='library',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='admin',
        ),
        migrations.DeleteModel(
            name='QRCODE',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'ADMIN'), (2, 'ADMINISTRATION')], default=1, max_length=50),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Administration',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='HOD',
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
